version: '3.9'
name: nextjs-learning
services:
  app:
    image: nginx:latest
    restart: always
    volumes:
      - ./logs:/var/log/nginx
      - ./app:/app
      - "./nginx/${RUN_MODE:-local}/:/etc/nginx/conf.d/:ro"
    ports:
      - '${HTTP_PORT:-80}:80'
    env_file:
      - ./.env

  # builder:
  #   image: node:16-alpine
  #   volumes:
  #     - ./app:/app
  #   working_dir: /app
  #   command: sh -c "yarn install --frozen-lockfile && yarn build && echo \"Installation finished\" "
  #   env_file:
  #     - ./.env
