version: '3.9'
services:
  vite:
    image: node:latest
    working_dir: /app
    volumes:
      - ./app:/app
    command: sh -c "npm install -g vite && npm install && vite"
    ports:
      - ${HTTP_PORT:-80}:3000
    env_file:
      - ./.env
